import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/components/navbar/navbar';
import Footer from '@/components/footer/footer';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <div className="container">
        <Navbar />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}

// function localFont(arg0: { src: string; variable: string; weight: string; }) {
//   throw new Error("Function not implemented.");
// }